# Generated by Django 6.0.2 on 2026-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakatuasoft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Login',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Senha',
            field=models.CharField(max_length=128),
        ),
    ]
