# Generated by Django 6.0.2 on 2026-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakatuasoft', '0002_alter_usuario_login_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='estacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_tranca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tranca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tranca_reservada',
            field=models.IntegerField(default=0),
        ),
    ]
